### ISSUE TITLE
[Chore] setup.py

### ISSUE THREAD

**Issue by noraj** [ShutdownRepo/uberfile#1]
Hi,

Could you provide a setup.py please?

https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py

**Comment by ShutdownRepo** [comment]
Thank you for the request, we'll work on it asap

**Comment by ShutdownRepo** [comment]
The setup.py should be working now @noraj 
Can you make sure it conforms to your needs?

**Comment by ShutdownRepo** [comment]
I'm closing this issue since the original mentioned issue has been closed already
Thank you for the feedback and help :+1:
